protoype v0.2 build (#20)
* first functionality
Items and Inventory

* Combat logic added
there is still an error C2556 and C040 when compiling

* fixing error

includes where commented out from previous commit

* removed comments

* (#19)

* (#19)

* vs project files

* commit all

* Closes #19

* Closes (#14)
Contains code for (#13)

* Completed Shop
Closes (#1)
Closes (#13)

AbilityTree missing